# Generated by Django 4.2.2 on 2023-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
